os: linux
dist: trusty
language: cpp
compiler: gcc

install:
  - export CXX="g++-6" CC="gcc-6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ./neuralnet_test
