sudo: required

language:
  - cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake

before_script:
  - export CC=gcc-6
  - export CXX=g++-6
  - gcc -v && g++ -v && cmake --version

script:
  - mkdir build
  - cmake ..
  - make
  - ./neuralnet_test
